version: "3"
services:
  webserver:
    build: 
      network: host
      context: apps/web/frontend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    restart: unless-stopped
    depends_on:
      - api

  api:
    build:
      context: apps/api
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      ENV: development
      DB_HOST: database
    volumes:
      - ./apps/api/src:/api/src
    depends_on:
      - database

  database:
    image: postgres:13.10-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: egoman
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
