name: Backend CI/CD

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /home/runner/work/egoman/egoman/apps/api

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Format
        run: poetry run invoke format --check

      - name: Lint
        run: poetry run invoke lint
